ssm-lang/sslang

app/Main.hs
package.yaml
src/Codegen/Codegen.hs
src/Common/Identifiers.hs
src/Front/Ast.hs
src/Front/Lowering.hs
src/Front/Parser.y
src/IR/IR.hs
src/IR/Lowering.hs
src/Types/Ast.hs
src/Types/Classes.hs
src/Types/TypeSystem.hs

In addition to implemeting this module, I've also made the following changes:
- Let-bindings now have a body. In the grammar, they are a more general form of sequencing.
- Wait statements may now wait on arbitrary expressions rather than just fixed identifiers. So something like `wait (if c then v1 else v2)` is possible.
- Ast and Classes type systems are now expliclty and separately defined.
There are still some things in the AST I don't really know how to desugar/lowering. Most of the desugaring should probably be handled elsewhere anyway. But this is a start, until we have some kind core-sslang in the AST.

Lower AST to IR

---

doc/sslang-lrm.tex

Add sections for expressions in LRM

---

regression-tests/tests/doubleblink2-main.c
src/IR/TypeInference.hs

In this PR:
- Change Int type back to 32-bit
- Update doubleblink2-main.c
- Add `PrimAdd` case to the `inferPrim` function

Add small fix on type inference and regression test

---

lib/ssm/Makefile
lib/ssm/include/ssm.h
lib/ssm/src/ssm-scheduler.c
lib/ssm/src/ssm-throw.c

NOTE: I intend on keeping these commits separate and rebase them, for cleaner upstreaming, so expect force pushes.
Fixes #35 by dropping `-U` flag (see commit message for details).
Still needs a solution to fix macOS's dodgy support for weak symbols.
One solution is to just case over the platform `[ "$(uname)" == "Darwin" ]` and manually specify `-Wl,-U,_ssm_throw` (following advice from https://stackoverflow.com/a/51755953), but this isn't exactly elegant, and we'll have to do this for every weak symbol. I'm looking into an alternate approach that involves weak aliases, which according to http://maskray.me/blog/2021-04-25-weak-symbol is less error prone (perhaps more uniformly supported?) across different toolchains. Will need some help testing this out; @hmontero1205 @XijiaoLi and …

Fix builds on macOS

---

lib/ssm/examples/blink-platformio-zephyr/platformio.ini
lib/ssm/examples/blink-platformio-zephyr/src/main.c
lib/ssm/examples/flipfloploopspec-platformio-zephyr/platformio.ini
lib/ssm/examples/flipfloploopspec-platformio-zephyr/src/main.c
lib/ssm/include/ssm.h

* Fix library to use nanosecond tick, for better platform-independence
* Modify examples to use ns time base

Use nanoseconds as time base (#1)

---

regression-tests/runtests.sh

Previously, the script would lead to a stale library, because it wasn't checking timestamps. This is exactly what Make is for, so we just unconditionally call make.
I tested that:
- It builds the library if it isn't there
- It rebuilds the library if one or more of its dependencies' timestamps are newer than the library
Verified using `touch` and inspecting `runtests.log`.

Always make libssm.a

---

regression-tests/tests/doubleblink.ssl
regression-tests/tests/doubleblink2.ssl

Since the type of `par` should be a tuple, the annotated return type of `main` function (`()`) is inconsistent with the actual type of its function body (`(), ()`). Since currently we not yet support handling tuple type inside codegen, add a dummy `()` at the end of function body so that its type matches the annotated return type.

Fix inconsistent type annotation in doubleblink

---

app/Main.hs
package.yaml
src/IR.hs
src/IR/IR.hs
src/IR/LambdaLift.hs
src/IR/Types/Poly.hs
test/ir-to-ir/Spec.hs
test/ir-to-ir/Tests/LiftProgramLambdasSpec.hs

Opening a draft to get some feedback in. Need advice on how to type lifted lambdas and general monadic programming critiques :)
Closes #32

Lift lambdas

---

src/Common/Compiler.hs
src/Front/Ast.hs
src/Front/ParseOperators.hs
src/Front/Parser.y
src/Front/Scanner.x
src/Front/Scope.hs
src/Front/Token.hs
src/IR/IR.hs
src/IR/LowerAst.hs
test/lib/Sslang/Test.hs
test/semant/Tests/ScopingSpec.hs
test/text/Tests/ParseLoopSpec.hs
test/text/Tests/ParsePatternMatchSpec.hs

Needed for #46, #49, #50, and #60---this syntax will allow user-defined ADTs, so that we can actually test those language features with real programs.
Will conflict a little with #49, which also makes changes to AST, parser, and related components to add syntax for declaring typeclases and defining their instances. @LeoQiao18 , I'm happy to help resolve those merge conflicts.
This PR is still a WIP, but should be done within the next day. Currently, I still have to:

Add type definition syntax

---

package.yaml
src/Common/Identifiers.hs
src/IR/IR.hs
src/IR/Types/Annotated.hs
src/IR/Types/Classes.hs
src/IR/Types/Flat.hs
src/IR/Types/Poly.hs
src/IR/Types/TypeSystem.hs
test/lib/Sslang/Test.hs
test/text/Tests/PrettyAstSpec.hs
test/trans/Tests/LiftProgramLambdasSpec.hs
test/trans/Tests/NormalizeSpec.hs

The following two programs are equivalent:
```
id a : a -> a = a
```
```
foo bar : baz -> baz = bar
```
and yet directly testing for exact equivalence will fail to recognize that these are not just semantically but _structurally_ equivalent.
This PR introduces a lightweight mechanism for telling the tests how not to split hairs over _specific_ identifiers, which may be compiler-generated and thus unstable, yet otherwise semanticaly insignificant.
This PR uses a technique first described in the ["Scrap Your Boilerplate" paper](https://www.microsoft.com/en-us/research/publication/scrap-your-boilerplate-with-class/), which had been sitting open in my browser for a few ~weeks~ months at this point. The technique is implemented in the [syb …

Mangle identifiers for testing equivalence

---

.github/actions/setup-build/action.yml
.github/workflows/doc.yml
.github/workflows/test.yml
README.md

Should come after #72 , but strictly speaking orthogonal
This will automatically deploy the code documentation to the `gh-pages` branch, which we will serve using GitHub Pages.
This PR also moves the Stack setup action (with its cached environment) into a separate, reusable action.

Automatically deploy Haddock documentation

---

.github/workflows/doc.yml

the old recipe was missing a build strategy that specifies a resolver and os, and that was hidden by the lack of a hook to run it during a PR.

Fix doc build CI

---

src/Codegen/Codegen.hs
src/IR/IR.hs
src/IR/SubstMagic.hs

Still incomplete, but the substitution logic is remarkably easy thanks to SYB-style generic programming.
I still need to tweak the lexer to accept identifiers like `#new` etc. and then fix the scope checker to allow those.

Substitute primitives

---

regression-tests/tests/inlinec-hello1.ssl
regression-tests/tests/inlinec-printf1.ssl
regression-tests/tests/inlinec-printf2.out
regression-tests/tests/inlinec-printf2.ssl
src/Codegen/Codegen.hs
src/Front/Ast.hs
src/Front/Parser.y
src/Front/Pattern/Anomaly.hs
src/Front/Pattern/Desugar.hs
src/Front/Scanner.x
src/Front/Scope.hs
src/Front/Token.hs
src/IR/HM.hs
src/IR/IR.hs
src/IR/LowerAst.hs
src/IR/TypeChecker.hs
test/text/Tests/ParseInlineCSpec.hs
test/text/Tests/ScanInlineCSpec.hs

Note that this PR includes brekaing changes to syntax. In particular, C definition blocks are now delimited by `$$$`; we're now using `$$` to delimit quoted C expression literals.

Support quoted inline C syntax

---

.gitignore
flake.lock
flake.nix
shell.nix

Stack and Nix have overlapping responsiblities when it comes to package management. Although Stack has the ability to integrate with Nix, I believe that it is not good to change the Stack configurations just to make this play well with Nix on Nix/NixOS systems.
It turns out that Tweag had a post that discusses this, providing a solution that integrates stack and nix in a "smooth and non-invasive" way. For more information, read the [blog](https://www.tweag.io/blog/2022-06-02-haskell-stack-nix-shell/). In order to have more explicit version pinning, this PR is using a version that extends on the idea in the blog and make use of Nix Flake. This is taken from a [section](https://docs.haskellstack.org/en/stable/nix_integration/#supporting-both-nix-and-non-nix-developers) in Stack's …

Non-invasive Nix + Nix Flake dev shell support

---

src/IR/Types.hs
src/IR/Types/Inference.hs
src/IR/Types/Type.hs
src/IR/Types/Typechecking.hs
src/IR/Types/Unification.hs
test/semant/Tests/TypeInferSpec.hs

Follow up to #103, addressing remaining concerns:

Support all pattern type annotations and check kinds

---

src/Common/Pretty.hs
src/IR.hs

Adds a compiler switch so the user can print IR after type inference with all type annotations visible. This is an ugly/lispy output but it can be helpful for development.

add switch for spaghetti, update old comment

---

doc/compile-build-run-cheatsheet.md
doc/lang-design/lowering-example.md

I've been sharing some resources with the language design group this semester over slack, but I know it would be better if there was a section in our doc repo they could consult instead of pinned slack messages. 
This PR adds 
- a folder for front end/lang-design related resources, and a file inside with information on the lowering pass
- a general build-test-compile-run cheat sheet to the doc directory, which is relevant to all sslang compiler developers.

add doc for language design folks

---

test/semant/Tests/TypeInferSpec.hs

Incorrect type inference unit test case. There are quite a bit of style changes from brittany as well.
Interestingly, the test case still passes even after the change.

Fix incorrect unit test case

---

src/Front.hs
src/IR/LowerAst.hs

This PR fixes the threading compiler of passes over the program so that the results of desugarStrings and desguarLists are fed correctly into the next pass, Pattern.desugarProgram.

stop skipping of list and string desugaring

---

src/Front/Ast.hs

This change will allow Max (on #119) and Anjali (on #118) to use `everywhere` over the AST, simplifying their passes .

Make AST implement typeable and data

---

src/Codegen/Codegen.hs
src/IR/IR.hs
src/IR/InsertRefCounting.hs
src/IR/LambdaLift.hs
src/IR/LowerAst.hs
src/IR/Types/Inference.hs

This PR adds recursive pattern matching in the IR and also fixes the later passes that are affected by this change.  All passes after type checking will assume that the patterns are non-recursive even though recursive patterns are expressible.
Recursive patterns in the IR are a prerequisite for moving the desugaring and exhaustion-checking to the IR, i.e., after type checking.

Allow recursive patterns in the IR

---

src/Codegen/Codegen.hs
src/IR/IR.hs
src/IR/InsertRefCounting.hs
src/IR/LambdaLift.hs
src/IR/Types/Inference.hs

Exception is introduced in IR to support dead branch for our desugaring algorithm migrated to IR.
Current implementation is using [`throw`](https://github.com/ssm-lang/sslang/blob/main/src/Codegen/LibSSM.hs#L99) with [`INTERNAL_ERROR`](https://github.com/ssm-lang/sslang/blob/main/src/Codegen/LibSSM.hs#L85)

Add exception

---

src/IR.hs
src/IR/OptimizePar.hs

Adds a stubbed-out pass over the IR for optimizing par called optimizePar.hs.
Matthew will edit this file (in a feature branch) in the future.
Currently, the pass doesn't do anything, so it's safe to push to main.

Add par stub

---

src/IR/Pretty.hs

Before:
```
puts_ (putc: (Int32 -> 'ir_t35))
(s: String): ((Int32 -> 'ir_t35) -> (String -> ())) =
let puts__: (String -> ()) = puts__puts__ putc
puts__ s
```
After:
```
puts_
(putc: (Int32 -> 'ir_t35))
(s: String): ((Int32 -> 'ir_t35) -> (String -> ())) =
let puts__: (String -> ()) = puts__puts__ putc
puts__ s
```
It is fix

Fix pretty printing of arguments

---

src/Codegen/Codegen.hs
src/Codegen/LibSSM.hs
src/Front/Ast.hs
src/Front/Identifiers.hs
src/Front/Parser.y
src/Front/Scanner.x
src/Front/Scope.hs
src/Front/Token.hs
src/IR/Constraint/Constrain/Expression.hs
src/IR/IR.hs
src/IR/LowerAst.hs

Doing so in the hackiest possible way...
Super quirks:
- `now` has type `Int64`, but it is code-genned into `ssm_now()`. This means that even though it _looks_ like a variable, it does not behave like one, in that its value depends on the instant in which you evaluate it.
- `@@ r` is our syntax for `last r`.
- Both of these primitives return `Int64`, which is not really a type we've used or tested at all. Right now I use `ssm_new_time()` to allocate them onto the heap (so that we still get an `ssm_value_t` handle to them, but sslang doesn't actually provide any way to read them directly. We'll use the cquote stuff to hack in some primitives, but until we have type classes/proper operator overloading, using `==` and `<` etc. on times just won't typecheck.
But damnit I need these …

Add preliminary support for now and last
